language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc
  -K $encrypted_b03605e8a180_key
  -iv $encrypted_b03605e8a180_iv
  -in .travis/travisci_rsa.enc
  -out .travis/travisci_rsa
  -d
- chmod 0600 .travis/travisci_rsa
- cp .travis/travisci_rsa ~/.ssh/id_rsa
- gem install fpm
after_success:
- ./.travis/deploy.sh
script:
- npm install
